function harmonics = harmonicDropZones()
harmonics = {...
    {'Cross', @harmonicCross},...
    {'Double T', @harmonicDoubleT},...
    {'L', @harmonicL},...
    {'C', @harmonicC},...
    {'T', @harmonicT},...
    {'O', @harmonicO}...
    {'Irregular', @harmonicIrregular}...
    {'Horizontal', @harmonicHorizontal}...
    {'Vertical', @harmonicVertical}...
    {'Cubic', @harmonicCubic}...
     {'CubicDiag', @harmonicCubicDiag}...
    {'CubicTest', @harmonicCubicTest}...
    {'HorizontalSym', @harmonicHorizontalSym}...
    };
end