function dropZones = harmonicDropZones()
dropZones = {...
    {'Cross', @dropZoneCross},...
    {'Double T', @dropZoneDoubleT},...
    {'L', @dropZoneL},...
    {'C', @dropZoneC},...
    {'T', @dropZoneT},...
    {'O', @dropZoneO}...
    {'Irregular', @dropZoneIrregular}...
    {'Horizontal', @dropZoneHorizontal}...
    {'Vertical', @dropZoneVertical}...
    {'Cubic', @dropZoneCubic}...
    };
end